#!/usr/bin/env node
/* =====================================================================
   make-lipsync.mjs — how loud each voice-over clip is, every 50 ms, so the
   characters' mouths can follow the voice (fx.js FX.mouth → game.js).

     node tools/make-lipsync.mjs

   Reads assets/vo/manifest.js, measures every clip with ffmpeg and writes
   assets/vo/lipsync.js: { "assets/vo/x.mp3": "0013578643100…" }, one digit
   (0 = silent … 9 = loud) per 50 ms. Run it after tools/generate-audio.mjs
   (that script runs it at the end). Needs ffmpeg on the PATH.
   ===================================================================== */
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const STEP_S = 0.05;                       // one value per 50 ms
const RATE = 8000;                         // analyse at 8 kHz: plenty for loudness
const QUIET_DB = -40, LOUD_DB = -8;        // RMS range mapped to 0 … 9

const sandbox = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(ROOT, "assets/vo/manifest.js"), "utf8"), sandbox);
const clips = [...new Set(Object.values(sandbox.window.VO_MANIFEST))];

function envelope(file) {
  const r = spawnSync("ffmpeg", ["-hide_banner", "-nostats", "-i", path.join(ROOT, file), "-af",
    `aresample=${RATE},asetnsamples=n=${RATE * STEP_S}:p=0,astats=metadata=1:reset=1,ametadata=print:key=lavfi.astats.Overall.RMS_level`,
    "-f", "null", "-"], { encoding: "utf8" });
  if (r.status !== 0) throw new Error(`ffmpeg failed on ${file}`);
  const out = (r.stdout || "") + (r.stderr || "");
  return [...out.matchAll(/RMS_level=(-?[\d.]+|-inf)/g)].map((m) => {
    const db = m[1] === "-inf" ? -120 : parseFloat(m[1]);
    return Math.max(0, Math.min(9, Math.round(((db - QUIET_DB) / (LOUD_DB - QUIET_DB)) * 9)));
  }).join("");
}

const map = {};
for (const c of clips) map[c] = envelope(c);
const body = Object.entries(map).map(([k, v]) => `  ${JSON.stringify(k)}: "${v}"`).join(",\n");
fs.writeFileSync(path.join(ROOT, "assets/vo/lipsync.js"),
  `/* Generated by tools/make-lipsync.mjs: clip → loudness every 50 ms (0–9), for the characters' mouths. */\nwindow.VO_LIPSYNC = {\n${body}\n};\n`);
console.log(`lipsync: ${clips.length} clips → assets/vo/lipsync.js`);
